version: '3.8'
services:
  pass-auth:
    image: ghcr.io/eclipse-pass/pass-auth:0.7.0-SNAPSHOT
    build:
      context: .
    restart: always
    env_file: .env
    ports:
      - '${AUTH_PORT}:${AUTH_PORT}'
