name: Release PASS-auth

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        required: true
        description: Version to release (e.g. 0.3.0)
      nextversion:
        required: true
        description: Next development version (e.g. 0.4.0-SNAPSHOT)

jobs:
  release:
    needs: bump-version
    if: github.repository == 'eclipse-pass/pass-auth'
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: ghcr.io/eclipse-pass/pass-auth

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node & Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Update project version to release version
        run: |
          yarn install --frozen-lockfile
          yarn version --new-version ${{ inputs.releaseversion }}

      - name: Tag and push release version, updating 'main' with new version
        run: |
          git tag ${{ inputs.releaseversion }}
          git push origin main
          git push origin ${{ inputs.releaseversion }}

      - name: Build pass-auth
        run: |
          yarn install --frozen-lockfile
          yarn run build

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push release version image
        run: docker push $DOCKER_IMAGE_NAME:${{ inputs.releaseversion }}

      - name: Bump project version to next dev version
        run: yarn version --new-version ${{ inputs.nextversion }}

      - name: Push version bump to GH
        run: git push origin main

      - name: Retag and push next dev image
        run: |
          docker tag $DOCKER_IMAGE_NAME:${{ inputs.releaseversion }} $DOCKER_IMAGE_NAME:${{ inputs.nextversion }}
          docker push $DOCKER_IMAGE_NAME:${{ inputs.nextversion }}
