name: 'Update pass-auth latest image'

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  update-latest-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Get project version
        id: project-version
        run: echo "VERSION=`npx -c 'echo $npm_package_version'`" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          yarn run build
          yarn run build:latest

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/eclipse-pass/pass-auth:${{ steps.project_version.outputs.version }}
          docker push ghcr.io/eclipse-pass/pass-auth:latest
