name: 'Update pass-auth latest image'

on:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  update-latest-image:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: ghcr.io/eclipse-pass/pass-auth

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Build
        run: yarn run build:latest

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push $DOCKER_IMAGE_NAME:latest
